# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0bd2b9561096d247f72ed26b2ad6fc7b9b8e4ddd2a0ed98df27f74d72555e11a29a4d371d7eff068e121a335fa471dc4865ad8569355462891a9d69f271edac

test:
  secret_key_base: fc424c745a4cbb68768d0cd13bafe9070f1221d76d711a1ad11c4d00b726c9b19a12058112cfc61ed254891d5b0343d6db1fe1ce618cdca24127d773f7637152

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
